### ISSUE TITLE
Slow interactivity on community boards

### ISSUE THREAD

**Issue by Tguntenaar** [NEAR-DevHub/neardevhub-bos#364]
**Describe the bug**

While migrating Kanban and Github to the new addon framework I noticed that the the input fields update with extreme lag.

**To Reproduce**
1. Go to [the test community](https://near.social/devhub.near/widget/app?page=community&handle=devhub-test)
2. Click on the github tab
3. Click on the `Configure` button. (make sure you are admin of the community to see it)
4. Try changing the title 
5. Wait `5 seconds`! to see the inputfield change

**Expected behavior**
It should work instantly like any other form.

**Screenshots**
<img width="953" alt="Screenshot 2023-10-30 at 16 30 39" src="https://github.com/near/neardevhub-widgets/assets/28901891/9fb55a71-a210-461d-b61b-be402b648293">

**Additional context**

The issue probably lies in the `deepFieldUpdate` function which calls it's self recursively, but I'm not sure. 

**Acceptance Criteria**
- [x] The old configurator at `src/gigs-board/entity/workspace/view/github/configurator.jsx` should be refactored to `src/devhub/entity/addon/github/Configurator.jsx`
- [ ] The configurator should work snappy

**Comment by Tguntenaar** [comment]
@ori-near could you decide on the priority for this ticket?

**Comment by Megha-Dev-19** [comment]
Hey @Tguntenaar  I opened this https://near.social/devhub.near/widget/app?page=community&handle=devhub-test&tab=Github
but I don't see configure option
I believe the UI is updated

**Comment by Tguntenaar** [comment]
@Megha-Dev-19 It's because only admins of that community can see the configure button. I've just granted admin privileges to your account, megha19.near. Please check now to see if the configure button is visible.

**Comment by Megha-Dev-19** [comment]
@Tguntenaar yeah I can see it now, thanks

**Comment by Megha-Dev-19** [comment]
@ori-near @Tguntenaar This is going to take longer time as estimated earlier, because it took me time to understand the data structure and secondly most of the components from devgovgigs are not yet migrated yet which are used here, so I will add them as well. And along with "Github", I will have to update for "Board" tab as well, since it also breaks with devhub components.
Then I will look into the issue with the state update which is mentioned in this ticket.
I'm increasing the size to 1 week, should be able to complete it within that.
Thanks

**Comment by Megha-Dev-19** [comment]
just fyi, will fix this issue as well 

![Image](https://github.com/near/neardevhub-widgets/assets/100185149/975da043-294b-410e-bfe2-298bc28a47ba)

**Comment by Megha-Dev-19** [comment]
hey @ori-near, so after quite some time, I was able to figure out the issue
when we update any text (it update the state), which causes all the components to rerender (because they are dependent on it), I tried to memoize it and few other hacks but it only made half a difference, so I asked @elliotBraem, he told me we had plan to separate the viewer and editor/configuration screen, but because of time crunch it wasn't implemented for github and kanban board
I believe that is the best solution we can do here, please let me know if I can proceed with that

**Comment by Megha-Dev-19** [comment]
Me and @ori-near discussed about the issue, and we plan on improving the whole UI/UX for github and kanban board, by providing a similar experience like that in blogs section -> one editor and preview tabs for better visibility.
I already raised the PR for migrating the code from devgogigs to devhub, but I think it's better to take the updated UI itself.
@ori-near, @ailisp please let me know if you want the migration deployed in the meantime (I will make some changes in the PR)
I will pick the UI updates later after completing the announcements UI, since that's a priority.
cc: @Tguntenaar
