### ISSUE TITLE
All announcements and discussions on DevHub

### ISSUE THREAD

**Issue by frol** [NEAR-DevHub/neardevhub-bos#692]
**Is your feature request related to a problem? Please describe.**

As a DevHub user, I would love to explore all the announcements in a single feed.

Today, I have to navigate to each individual community or monitor global NEAR Social Feed to see new posts on DevHub, but neither of these options provide me with a good picture of what is happening.

**Describe the solution you'd like**

I suggest to implement "DevHub Feed" (instead of the current "Activity feed"), which will bring all announcements (and maybe discussions) together.

The technical implementation is super simple: we need to make `community.devhub.near` account to subscribe to all the subaccounts, and then we can render NEAR Social Feed component as if it is `community.devhub.near` account is looking at their NEAR Social Feed.

**Comment by frol** [comment]
The contract side is ready and `community.devhub.near` is subscribed to all the subaccounts, so only frontend is left to display the feed as if the user is logged in as `community.devhub.near`.

**Comment by Tguntenaar** [comment]
@frol the PR is almost ready, for some reason the "All" tab only shows the announcements. Looks like the [render Item here](https://github.com/Tguntenaar/neardevhub-widgets/blob/1c87a8a3cc8f071ef2d5529dc093bc6087f737b9/src/devhub/components/feed/SubscribedFeed.jsx#L167) can't have two different items at the same time because it the announcements and discussions tab do work seperately.

See the [preview](https://near.org/thomasguntenaar.near/widget/app?page=announcements)
