### ISSUE TITLE
Create Proposal Link RFP – User should only be allowed to select active RFPs

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#806]
**Affected Portal:**
Infrastructure

**Description:**
Currently, when a user creates a proposal they are able to search and choose all RFPs (e.g. 1 through 6):
![Screenshot 2024-06-03 at 9 16 43 AM](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/80384550-4180-4f17-b804-188f836b81ac). However, the description states that `You can only link to active RFPs in the “Accepting Submission” stage. 

**User Type:**
Logged in users who are creating a proposal

**Reproduction Steps**
1. Go to Infrastructure, click create proposal.
2. Click on the Search RFP dropdown under the first Link RFP (Optional) field.
3. User is able to click on all RFPs, even ones that are not in "Accepting Submission" stage

**Expected behavior**
User should only be able to click on RFPs in the "Accepting Submission" stage. Perhaps we should gray out inactive RFPs in the dropdown menu. Or alternatively only show ones that are in the "Accepting Submission" stage.

**Priority**
Low (P3) – Minor inconvenience

**Environment Details**
- Device: Desktop
- OS: Mac
- Browser: Safari
- Version: Version 17.3.1 (19617.2.4.11.12)

**Additional Context**

**Comment by Megha-Dev-19** [comment]
hey @ori-near user will be allowed only active RFPs
you're an admin, you said that admin should be allowed to link/unlink at any stage of RFPs, that's why you see all RFPs
you can login using other account and it will show only "Accepting submissions" one, here is a screenshot of same
<img width="1512" alt="image" src="https://github.com/NEAR-DevHub/neardevhub-bos/assets/100185149/441389ce-82ea-443e-bc04-c1708da2163f">
