### ISSUE TITLE
Admin unable to change proposal status, sees infinite loader screen

### ISSUE THREAD

**Issue by Megha-Dev-19** [NEAR-DevHub/neardevhub-bos#969]
**Affected Portal:**
Infrastructure, but need to investigate if others are impacted

**Description:**
Trentin reported that when he tried to change the status of any proposal on the infrastructure committee, he sees an infinite loader screen.

**User Type**
Admin

**Reproduction Steps**
1. Open Infra Committee: https://infrastructure-committee.near.page/
2. Select NEAR gateway: https://dev.near.org/infrastructure-committee.near/widget/app
3. Navigate to proposals: https://dev.near.org/infrastructure-committee.near/widget/app?page=proposals
4. Click on any proposal, such as: https://dev.near.org/infrastructure-committee.near/widget/app?page=proposal&id=51
5. Change status (e.g. Review to Draft) and click save
6. See infinite loading screen

**Expected Behavior**
Admin should be able to change proposal status without seeing error screens.

**Visual Reference**
https://github.com/user-attachments/assets/54d5d641-6f4e-431e-abf5-beb3d46298ce

# Technical Notes
@Megha-Dev-19:
- For invalid URLs like `https://dev.near.org/infrastructure-committee.near/widget/app?page=proposal`, if the “page” parameter is invalid instead of showing the spinner, we can display something like “Page not found. `[Go to the home page](link)`”

**Comment by Tguntenaar** [comment]
# Investigated

I was not able to reproduce this bug on `events-committee.near`. 

@Megha-Dev-19 I did find out that Events committee is using the `versionedtimeline` while the infra committee is using `timelinev1`. That could explain why I can't reproduce it on events committee.

After investigation I found that the error is 
```
The account infrastructure-committee.near wouldn't have enough balance to cover storage, required to have 166915562072304400000003 yoctoNEAR more
```
![Image](https://github.com/user-attachments/assets/10879eb1-dea5-4899-a7f1-a9ea54fe2897)

As @ori-near had found as well. If you use mynear wallet you will see that error. If you use meteor wallet or another wallet without redirect submitting this transaction will keep spinning.

![Image](https://github.com/user-attachments/assets/9d17b729-855b-4220-b982-58f7bad5debe)

# Solution

Depost NEAR to the `infrastructure-committee.near` account.

# Next steps

We should create an issue to describe showing the error message that we see in on mynearwallet. Because now there was no way we could find out what went wrong with meteor wallet.
